server:
  port: 8080

rate-limiter:
  redis:
    host: localhost
    port: 6379
    password: ""
    database: 0
  user-id-header: X-User-Id
  default-limit: 10
  default-duration: 1
  default-time-unit: MINUTES

spring:
  redis:
    host: localhost
    port: 6379